### ISSUE TITLE
Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by BxinoProductions** [Nathaniel-VFX/Discord.js-v14-Command-Handlers#11]
i was in class so i cudent answer 
im getting this 

<rejected> TypeError: Cannot read properties of undefined (reading 'name')
      at /home/runner/BxinoUtilities/commands/prefix/Info/help.js:10:87
      at /home/runner/BxinoUtilities/node_modules/@discordjs/collection/dist/collection.cjs:174:14
      at Function.from (<anonymous>)
      at Map.map (/home/runner/BxinoUtilities/node_modules/@discordjs/collection/dist/collection.cjs:172:18)
      at Object.run (/home/runner/BxinoUtilities/commands/prefix/Info/help.js:10:45)
      at Client.<anonymous> (/home/runner/BxinoUtilities/events/Guild/messageCreate.js:60:15)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

how to fix

**Comment by D99-1** [comment]
Define 'name' 🤯

**Comment by FisbanRegner** [comment]
with out code it hard to say what the problem actually is, but it appears that in line 10 of help.js you are looking for 'name' and its undefined.

**Comment by sulvii** [comment]
Can you share your code?

**Comment by Nathaniel-VFX** [comment]
Your file locations is /commands/prefix/info/help.js
But the handler is suitable for the /commands/info/help.js
The code cannot access the name properties in your file due to different file location, so you can either change the code of the handler or remove your prefix folder.
