### ISSUE TITLE
slash commands?

### ISSUE THREAD

**Issue by exkludera** [Nathaniel-VFX/Discord.js-v14-Command-Handlers#21]
```
DiscordAPIError[10002]: Unknown Application
    at SequentialHandler.runRequest (C:\Users\henkez\Downloads\Discord.js-v14-Command-Handlers-main\node_modules\@discordjs\rest\dist\index.js:708:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (C:\Users\henkez\Downloads\Discord.js-v14-Command-Handlers-main\node_modules\@discordjs\rest\dist\index.js:511:14)
    at async C:\Users\henkez\Downloads\Discord.js-v14-Command-Handlers-main\handlers\slashCommand.js:46:5 {
  rawError: { message: 'Unknown Application', code: 10002 },
  code: 10002,
  status: 404,
  method: 'put',
  url: 'https://discord.com/api/v9/applications/874532279635030038/guilds/931644627713421312/commands',
  requestBody: {
    files: undefined,
    json: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  }
}
```

downloaded main branch and installed the packages listed in the repository

I guess it's outdated? or lmk if i'm doing something wrong 😐

**Comment by exkludera** [comment]
`CLIENT_ID=`

lol... did not know it needed the application id? should say that instead of client
